### ISSUE TITLE
ResponseCaching Checklist

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/ResponseCaching#10]
### Infrastructure work
- [x] Reserve package name https://github.com/aspnet/ResponseCaching/pull/12
- [x] Builds, CI, packages.csv, etc. https://github.com/aspnet/ResponseCaching/pull/12
- [x] Update to ASP.NET Core 1.0.0 https://github.com/aspnet/ResponseCaching/pull/12

### Middleware
- Default cache behaviours
 - [x] based on HTTP Headers (RFC 7234) https://github.com/aspnet/ResponseCaching/pull/15
 - [x] Request/Response are cacheable, cacheability based on state: headers, expiry, ... https://github.com/aspnet/ResponseCaching/pull/15
 - [x] Heuristics based freshness (RFC) - https://github.com/aspnet/ResponseCaching/pull/15
 - [x] 📂 strip/send warnings (RFC) https://github.com/aspnet/ResponseCaching/issues/41
 - [x] :x: Corrected age value (RFC) probably not an issue since our closeness to the endpoint means the apparent age is accurate enough
 - [x] 📂 POST responses invalidates cache (RFC) - https://github.com/aspnet/ResponseCaching/issues/38
 - [x] 📂 no-cache fields (RFC) - https://github.com/aspnet/ResponseCaching/issues/40
 - [x] :x: no-transform (RFC) No work needs to be done here since we don't transform the payload.
- Options
 - [x] max size to buffer https://github.com/aspnet/ResponseCaching/pull/25
 - [x] path case sensitivity https://github.com/aspnet/ResponseCaching/pull/26
- Conditional requests (respond to validation requests)
 - [x] `IfNotModifiedSince`, `IfNoneMatch` https://github.com/aspnet/ResponseCaching/pull/22
- Revalidation with endpoint
 - [x] 📂eviction, freshness update (RFC, ASPNET, Orchard) - https://github.com/aspnet/ResponseCaching/issues/39
- Cache invalidation 
 - [x] 📂 cache dependency, invalidation by endpoint (RFC, Orchard) - https://github.com/aspnet/ResponseCaching/issues/38
- 📂Partial responses (RFC, ASPNET) - https://github.com/aspnet/ResponseCaching/issues/36
 - [x] Consolidating partial responses
 - [x] Serve portions of full cached responses per range header
- [x] 📂Gated incoming requests (Orchard) https://github.com/aspnet/ResponseCaching/issues/37

### Storage
- IDistributedCache, IMemroyCache
 - [x] Storage provider interface https://github.com/aspnet/ResponseCaching/pull/14
 - [x] Serialization, binary serialization https://github.com/aspnet/ResponseCaching/pull/14
- [x] 📂 FileSystem based storage (ASPNET) - https://github.com/aspnet/ResponseCaching/issues/8
- Key generation
 - [x] Path Method, VaryBy https://github.com/aspnet/ResponseCaching/pull/12
 - [x] Custom key producer via delegate (ASPNET) https://github.com/aspnet/ResponseCaching/pull/16
- Vary By
 - [x] Headers https://github.com/aspnet/ResponseCaching/pull/14
 - [x] Location (Orchard) - user extensible
 - [x] Auth (Orchard) - user extensible
 - [x] Hash of POST data (ASPNET)  - user extensible
 - [x] QueryString (ASPNET, Orchard) https://github.com/aspnet/ResponseCaching/pull/21
 - [x] Encoding (ASPNET) - user extensible
 - [x] Delegate for more custom vary by (ASPNET) https://github.com/aspnet/ResponseCaching/pull/16
- Diagnostics
 - Cache hit ratio, maybe this should be in Caching?

### Endpoint
- Communication with endpoint
  - [x] cache-control header https://github.com/aspnet/ResponseCaching/pull/15
- [x] Cache invalidation - https://github.com/aspnet/ResponseCaching/issues/38

### Performance
- [x] 📂 Chunking of cached responses in storage to prevent allocations on LOH #7

**Comment by JunTaoLuo** [comment]
Since most of the work here has been done, I'll be filing individual issues for the remaining items and closing this aggregate issue.

**Comment by JunTaoLuo** [comment]
All remaining issues have been filed. closing
